export const FETCH_MENU_REQUEST = 'FETCH_MENU_REQUEST';
export const FETCH_MENU_SUCCESS = 'FETCH_MENU_SUCCESS';
export const FETCH_MENU_FAILURE = 'FETCH_MENU_FAILURE';

export const ADD_TO_CART = 'ADD_TO_CART';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM';
export const CLEAR_CART = "CLEAR_CART";

export const PLACE_ORDER = 'PLACE_ORDER';
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS';

export const FETCH_USERS_REQUEST = 'FETCH_MENU_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_MENU_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_MENU_FAILURE';
export const FETCH_USER_REQUEST = 'FETCH_MENU_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_MENU_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_MENU_FAILURE';
export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const EDIT_USER = 'EDIT_USER';

export const FETCH_BLOGS_REQUEST = 'FETCH_BLOGS_REQUEST';
export const FETCH_BLOGS_SUCCESS = 'FETCH_BLOGS_SUCCESS';
export const FETCH_BLOGS_FAILURE = 'FETCH_BLOGS_FAILURE';
export const FETCH_BLOG_REQUEST = 'FETCH_BLOG_REQUEST';
export const FETCH_BLOG_SUCCESS = 'FETCH_BLOG_SUCCESS';
export const FETCH_BLOG_FAILURE = 'FETCH_BLOG_FAILURE';
export const ADD_BLOG = 'ADD_BLOG';
export const ADD_BLOG_SUCCESS = 'ADD_BLOG_SUCCESS';
export const DELETE_BLOG = 'DELETE_BLOG';
export const EDIT_BLOG = 'EDIT_BLOG';

export const AUTHENTICATION_REQUEST = 'AUTHENTICATION_REQUEST';
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_RETRY = 'AUTHENTICATION_RETRY';
export const UNAUTHENTICATE = 'UNAUTHENTICATE';

export const ADMIN_AUTHENTICATION_REQUEST = 'AUTHENTICATION_REQUEST';
export const ADMIN_AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';
export const ADMIN_AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const ADMIN_AUTHENTICATION_RETRY = 'AUTHENTICATION_RETRY';
export const ADMIN_UNAUTHENTICATE = 'UNAUTHENTICATE';

export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';